version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules  # avoid node_modules conflict
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
